version: '3.9'

volumes:
  db_data:
    driver: local

services:
  app:
    build:
      context: .
    container_name: library_service
    depends_on:
      - library_service_db
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - '8080:8080'

  library_service_db:
    image: postgres
    container_name: library_service_db
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    volumes:
      - ./src/main/resources/db:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data