spring:
  application:
    name: library-service
  liquibase:
    change-log: db/changelog/changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: validate
  mvc:
    hiddenmethod:
      filter:
        enabled: true